openapi: 3.0.0

info:
  title: NOVA v15 Common
  version: 0.0.1-SNAPSHOT
  description: >-
    OpenAPI specification contains all those types that are valid for multiple REST resources of NOVA.
    
    Please be aware that this specfication does not offer any operations but is a pure source basic data types.
  contact:
    name: NOVA Development Team
    url: 'https://tillmannschall.github.io/nova/'
    email: nova@sbb.ch
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  # BusinessLogService
  /nova/v15/businesslog/{businessLogID}:
    get:
      operationId: getBusinessLog
      parameters:
        - name: businessLogID
          in: path
          description: >- 
            TODO Please add comment
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: >- 
            <html>
              <head>
            		<style>
            			p {padding:0px; margin:0px;}
            		</style>
            	</head>
              <body>
            Authorization header is required for all requests to NOVA. In compliance with SBB / NOVA Zero-Trust policy, starting from NOVA 15, all clients need to have an authentication for the channel itself and for the acting user. Both information need to be provided within the authorization token.    
            <br>    
            <br>NOVA will still support requests from anonymous end users but in this case all features that somehow need access to personal data (e.g. TKID) will not be available.    
            <br></body>
            </html>
          required: true
          schema:
            type: string
        - name: Conversation-Id
          in: header
          description: >- 
            <html>
              <head>
            		<style>
            			p {padding:0px; margin:0px;}
            		</style>
            	</head>
              <body>
            Conversation id is used to group together a sequence of REST calls to NOVA. All requests that belong to the same business process are supposed to have the same conversation id.</body>
            </html>
          required: false
          schema:
            type: string
        - name: Accept-Language
          in: header
          description: >- 
            <html>
              <head>
            		<style>
            			p {padding:0px; margin:0px;}
            		</style>
            	</head>
              <body>
            Preferred language of the requesting client. Attribute can be filled according to logic of HTTP Header field as defined on <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language">Accept-Language</a>. This explicitly includes weighting of languages (e.g. &quot;fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5&quot;).    
            <br>    
            <br>However please be aware that NOVA in general only supports the languages &quot;de&quot;, &quot;fr&quot;, &quot;it&quot; and &quot;en&quot;.    
            <br>    
            <br>Even though the parameter is optional it's strongly recommended to provide it in requests, if not default language will be used. Please be aware that NOVA's default language is not explicitly defined and may change over time without prior notice.</body>
            </html>
          required: false
          schema:
            type: string
        - name: Date-Shift
          in: header
          description: >- 
            <html>
              <head>
            		<style>
            			p {padding:0px; margin:0px;}
            		</style>
            	</head>
              <body>
            Header field can be used to modify the date part of the request time stamp. It can either be defined as an absolute date in format YYYY-MM-DD or as an relative shift using '+' / '-' in combination with a shift value as absolute number for the amount of days that should be shifted (e.g. &quot;-7&quot; or &quot;+2&quot; days).    
            <br>    
            <br>Date shift is only supported on non productive environments.</body>
            </html>
          required: false
          schema:
            type: string
        - name: Time-Shift
          in: header
          description: >- 
            <html>
              <head>
            		<style>
            			p {padding:0px; margin:0px;}
            		</style>
            	</head>
              <body>
            Header field can be used to modify the time part of the request time stamp. It can either be defined as an absolute time in format HH:mm:ss or as an relative shift using '+' / '-' in combination with a shift value as absolute number for the amount of minutes that should be shifted (e.g. &quot;-31&quot; or &quot;+120&quot; minutes).    
            <br>    
            <br>Time shift is only supported on non productive environments.</body>
            </html>
          required: false
          schema:
            type: string
      responses:
        '200':
          description: >- 
            TODO Please add comment
          content:  
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessLog'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '403':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
        'default':
          $ref: '#/components/responses/ErrorResponse'


components:
  responses:
    # ch.voev.nova.services.nova.v15.common.ErrorResponse
    ErrorResponse:
      description: >-
        Generic error response that is used by all NOVA services to indicate technical problems. Returned data structure is compliant with Problem JSON.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'


  schemas:
    # ch.voev.nova.services.nova.v15.common.NOVARequest
    NOVARequest:
      discriminator:
        propertyName: objectType
        mapping:
          NOVARequest: '#/components/schemas/NOVARequest'
          OfferRequest: '../pricing/nova-pricing.yaml#/components/schemas/OfferRequest'
      type: object
      properties:
        objectType:
          description: Attribute is used as discriminator for inheritance between data types.
          type: string
      required:
        - objectType
    # ch.voev.nova.services.nova.v15.common.Message
    Message:
      description: >-
        Type represents a message that can be returned by any NOVA REST resource. The message contains a literal description as well as a message ID that can be used to identify the message.
        
         Please be aware that depending on the message not localizations for all languages will be provided.
      type: object
      properties:
        messageID: 
          type: integer
          format: int32
          minimum: 0
          exclusiveMinimum: true
          readOnly: true
        messageType: 
          $ref: '#/components/schemas/MessageType'
        localizations: 
          type: array
          items:
            $ref: '#/components/schemas/LocalizedText'
          minItems: 0
        defaultText: 
          $ref: '#/components/schemas/LocalizedText'
      required:
        - messageID
    # ch.voev.nova.services.nova.v15.common.LocalizedText
    LocalizedText:
      type: object
      properties:
        text: 
          type: string
          readOnly: true
        language: 
          type: string
          readOnly: true
    # ch.voev.nova.services.nova.v15.common.Problem
    Problem:
      description: >-
        Data structure represents a technical problem that occurred during a REST call (aka as Problem JSON). It is compatible with problem structure as it is defined in RFC7807 (https://datatracker.ietf.org/doc/html/rfc7807).
        
        In NOVA context problems are only used to indicate technical problems. Business problems need to provide way more context and thus will be part of response data structure.
        
      type: object
      properties:
        title: 
          description: >-
            A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
            Consumers MUST use the "type" string as the primary identifier for the problem type; the "title" string is advisory and included only for users who are not aware of the semantics of the URI and do not have the ability to discover them.
          type: string
          nullable: false
          readOnly: true
        status: 
          description: >-
            The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
          type: integer
          format: int32
          nullable: false
          readOnly: true
        type: 
          description: >-
            A URI reference [RFC3986] that identifies the problem type. When this member is not present, its value is assumed to be "about:blank".
          type: string
          nullable: false
          readOnly: true
          default: "about:blank"
        detail: 
          description: >-
            A human-readable explanation specific to this occurrence of the problem.
          type: string
          readOnly: true
        instance: 
          description: >-
            A URI reference that identifies the specific occurrence of the problem.  It may or may not yield further information if dereferenced.
          type: string
          readOnly: true
      required:
        - title
        - status
        - type
    # ch.voev.nova.services.nova.v15.common.NOVAResponse
    NOVAResponse:
      discriminator:
        propertyName: objectType
        mapping:
          NOVAResponse: '#/components/schemas/NOVAResponse'
          OfferResponse: '../pricing/nova-pricing.yaml#/components/schemas/OfferResponse'
      type: object
      properties:
        objectType:
          description: Attribute is used as discriminator for inheritance between data types.
          type: string
        messages: 
          type: array
          items:
            $ref: '#/components/schemas/Message'
          minItems: 0
      required:
        - objectType
    # ch.voev.nova.services.nova.v15.common.DidokCode
    DidokCode:
      description: >-
        Data structure describes codes for different kinds of sales locations. These codes are managed by a system outside NOVA named DIDOK. In NOVA DIDOK codes are used to identify point of sales physical as well as logical ones.
      type: object
      properties:
        code: 
          description: >-
            Code value of a sales location as it was defined by DIDOK.
          type: integer
          format: int32
          minimum: 0
          exclusiveMinimum: true
          readOnly: true
      required:
        - code
    # ch.voev.nova.services.nova.v15.common.BusinessLog
    BusinessLog:
      type: object
    # ch.voev.nova.services.nova.v15.common.PostalAddress
    PostalAddress:
      type: object
      properties:
        countryCode: 
          description: >-
            ISO 3166 alpha-2 country code.
          type: string
          minLength: 2
          maxLength: 2
          readOnly: true
        street: 
          type: string
          maxLength: 30
        supplement: 
          type: string
          maxLength: 30
        postalCode: 
          type: string
          maxLength: 15
        city: 
          type: string
          minLength: 1

          maxLength: 30
      required:
        - city

    
    # ch.voev.nova.services.nova.v15.common.TimeUnit
    TimeUnit:
      description: >-
        <html>
          <head>
        		<style>
        			p {padding:0px; margin:0px;}
        		</style>
        	</head>
          <body>
        Enumeration represents time units.    
        <br>    
        <br>NOVA 14 Mapping:    
        <br>- nova-base.xsd: ZeitEinheit    
        <br></body>
        </html>
      type: string
      enum:
        - MINUTES
        - HOURS
        - DAYS
        - WEEKS
        - MONTHS
        - YEARS

    # ch.voev.nova.services.nova.v15.common.MessageType
    MessageType:
      description: >-
        Enumeration defines the possible types of messages that can be returned from calls to NOVA REST resources.
      type: string
      enum:
        - INFO
        - WARNING
        - ERROR

    # ch.voev.nova.services.nova.v15.common.BusinessLogLevel
    BusinessLogLevel:
      type: string
      enum:
        - OFF
        - SUMMARY
        - INFO
        - DEBUG

